-- CREATE DATABASE typeface;

\c typeface;

DROP TABLE IF EXISTS file_info;

CREATE TABLE file_info (
                           db_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           id VARCHAR(255),
                           name VARCHAR(255),
                           url VARCHAR(255),
                           size BIGINT,
                           file_type VARCHAR(255),
                           created TIMESTAMP,
                           PRIMARY KEY (db_id)
);


